SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Hayvanlar](
	[Hayvan_ID] [int] IDENTITY(1,1) NOT NULL,
	[HayvanTur] [varchar](50) NOT NULL,
	[HayvanYas] [int] NULL,
	[HayvanCinsiyet] [varchar](10) NULL,
	[Musteri_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Hayvanlar] ADD PRIMARY KEY CLUSTERED 
(
	[Hayvan_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Hayvanlar]  WITH CHECK ADD FOREIGN KEY([Musteri_ID])
REFERENCES [dbo].[Musteriler] ([Musteri_ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
