SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tedavi_Hastalik](
	[Tedavi_ID] [int] NOT NULL,
	[Hastalik_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Tedavi_Hastalik] ADD PRIMARY KEY CLUSTERED 
(
	[Tedavi_ID] ASC,
	[Hastalik_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Tedavi_Hastalik]  WITH CHECK ADD FOREIGN KEY([Hastalik_ID])
REFERENCES [dbo].[Hastalik] ([Hastalik_ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Tedavi_Hastalik]  WITH CHECK ADD FOREIGN KEY([Tedavi_ID])
REFERENCES [dbo].[Tedaviler] ([Tedavi_ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
