SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tedavi_Ilac](
	[Tedavi_ID] [int] NOT NULL,
	[Ilac_ID] [int] NOT NULL,
	[IlacDozu] [varchar](50) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Tedavi_Ilac] ADD PRIMARY KEY CLUSTERED 
(
	[Tedavi_ID] ASC,
	[Ilac_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Tedavi_Ilac]  WITH CHECK ADD FOREIGN KEY([Ilac_ID])
REFERENCES [dbo].[Ilaclar] ([Ilac_ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Tedavi_Ilac]  WITH CHECK ADD FOREIGN KEY([Tedavi_ID])
REFERENCES [dbo].[Tedaviler] ([Tedavi_ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
